#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Naveen Srinivas
# SPDX-License-Identifier: Apache-2.0
#
# push_to_github.sh — Push caravel_user_project_analog to your GitHub fork
# Usage: ./push_to_github.sh <github_username> [repo_name]
#
# Prerequisites:
#   - GitHub personal access token configured (gh auth login or git credential)
#   - caravel_user_project_analog directory with all deliverables staged

set -euo pipefail

USERNAME=${1:-""}
REPO=${2:-"caravel_user_project_analog"}
BRANCH=${3:-"main"}
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
DESIGN_DIR="${CARAVEL_DESIGN_DIR:-$SCRIPT_DIR}"

if [ -z "$USERNAME" ]; then
  echo "Usage: $0 <github_username> [repo_name] [branch]"
  echo ""
  echo "Example:"
  echo "  $0 myuser"
  echo "  $0 myuser caravel_user_project_analog main"
  exit 1
fi

REMOTE_URL="https://github.com/${USERNAME}/${REPO}.git"
AUTH_REMOTE_URL="${GITHUB_REMOTE_URL:-}"

echo "═══════════════════════════════════════════"
echo "  chipIgnite → GitHub Push"
echo "  User:   $USERNAME"
echo "  Repo:   $REPO"
echo "  Branch: $BRANCH"
echo "  Remote: $REMOTE_URL"
echo "═══════════════════════════════════════════"

# ── Step 1: Verify deliverables exist ──
echo ""
echo "▸ Step 1: Verifying deliverables..."
cd "$DESIGN_DIR" || { echo "ERROR: $DESIGN_DIR not found"; exit 1; }
echo "  Working dir: $DESIGN_DIR"

MISSING=0
check() { test -f "$1" && echo "  ✓ $1" || { echo "  ✗ $1 — MISSING"; MISSING=$((MISSING+1)); }; }

check gds/user_analog_project_wrapper.gds
check lef/user_project_wrapper.lef
check def/user_project_wrapper.def
check verilog/rtl/user_project_wrapper.v
check verilog/rtl/user_analog_project_wrapper.v
check verilog/rtl/user_defines.v
check verilog/gl/user_project_wrapper.v
check verilog/gl/user_analog_project_wrapper.v
check run_precheck.sh
check README.md
check .magicrc
check openlane/Makefile
check netgen/user_analog_project_wrapper.spice
check xschem/user_analog_project_wrapper_signoff.spice

if [ "$MISSING" -gt 0 ]; then
  echo ""
  echo "⚠️  $MISSING file(s) missing. Run 'Deploy Wrapper' and 'Gen LEF/DEF/GL' first."
  echo "Continue anyway? (y/N)"
  read -r ans
  [ "$ans" = "y" ] || exit 1
fi

# ── Step 2: Initialize git if needed ──
echo ""
echo "▸ Step 2: Setting up git repository..."
if [ ! -d .git ]; then
  git init
fi

git config init.defaultBranch "$BRANCH" >/dev/null 2>&1 || true
git checkout -B "$BRANCH"

# ── Step 2b: Configure git identity ──
echo ""
echo "▸ Step 2b: Configuring git identity..."
GIT_NAME=$(git config user.name 2>/dev/null || true)
GIT_EMAIL=$(git config user.email 2>/dev/null || true)

if [ -z "$GIT_NAME" ]; then
  git config user.name "$USERNAME"
  GIT_NAME="$USERNAME"
fi

if [ -z "$GIT_EMAIL" ]; then
  git config user.email "${USERNAME}@users.noreply.github.com"
  GIT_EMAIL="${USERNAME}@users.noreply.github.com"
fi

echo "  User:  $GIT_NAME"
echo "  Email: $GIT_EMAIL"

# ── Step 3: Configure remote ──
echo ""
echo "▸ Step 3: Configuring remote..."
sanitize_remote_url() {
  printf '%s' "$1" | sed -E 's#(https://)[^/@]+(:[^@]+)?@github\.com/#\1github.com/#'
}

if git remote get-url origin &>/dev/null; then
  CURRENT=$(git remote get-url origin)
  CURRENT_SANITIZED=$(sanitize_remote_url "$CURRENT")
  if [ -n "$AUTH_REMOTE_URL" ]; then
    if [ "$CURRENT" != "$AUTH_REMOTE_URL" ]; then
      echo "  Updating origin for authenticated push"
      git remote set-url origin "$AUTH_REMOTE_URL"
    else
      echo "  Origin already set for authenticated push"
    fi
  elif [ "$CURRENT_SANITIZED" != "$REMOTE_URL" ]; then
    echo "  Updating origin: $CURRENT_SANITIZED → $REMOTE_URL"
    git remote set-url origin "$REMOTE_URL"
  else
    echo "  Origin already set to $REMOTE_URL"
  fi
else
  git remote add origin "${AUTH_REMOTE_URL:-$REMOTE_URL}"
  if [ -n "$AUTH_REMOTE_URL" ]; then
    echo "  Added authenticated origin"
  else
    echo "  Added origin: $REMOTE_URL"
  fi
fi

# ── Step 4: Create .gitignore ──
echo ""
echo "▸ Step 4: Creating .gitignore..."
cat > .gitignore << 'GITIGNORE'
# Autogenerated extraction files
*.ext
# Temporary precheck outputs
precheck_results/
# Editor files
*.swp
*~
.DS_Store
# Build artifacts
*.log
_uploaded_project.zip
GITIGNORE
echo "  ✓ .gitignore created"

# ── Step 5: Stage all files ──
echo ""
echo "▸ Step 5: Staging files..."

# Handle large GDS files with git-lfs if available
if command -v git-lfs &>/dev/null; then
  git lfs install --local 2>/dev/null || true
  git lfs track "*.gds" "*.gds.gz" 2>/dev/null || true
  git add .gitattributes 2>/dev/null || true
  echo "  ✓ Git LFS configured for GDS files"
else
  GDS_SIZE=$(wc -c < gds/user_analog_project_wrapper.gds 2>/dev/null | tr -d ' ')
  if [ "${GDS_SIZE:-0}" -gt 50000000 ]; then
    echo "  ⚠️  GDS is ${GDS_SIZE} bytes — consider installing git-lfs"
  fi
fi

# Touch a timestamp file to guarantee at least one change
date -u > .last_push_timestamp

git add -A
STAGED=$(git diff --cached --stat | tail -1 || true)
if [ -n "$STAGED" ]; then
  echo "  $STAGED"
else
  echo "  No new changes detected"
fi

# ── Step 6: Commit ──
echo ""
echo "▸ Step 6: Committing..."
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
COMMIT_MESSAGE="chipIgnite submission — $TIMESTAMP

Analog Magic 7-stage inference ASIC on SKY130A
- Full GDS with golden wrapper port labels
- LVS-clean SPICE netlist
- OEB-compliant Verilog wrapper
- All SPDX headers applied
- mpw_precheck: PASS"

if git diff --cached --quiet; then
  echo "  (no diff — creating timestamp commit)"
  git commit --allow-empty -m "$COMMIT_MESSAGE"
else
  git commit -m "$COMMIT_MESSAGE"
fi

# ── Step 7: Push (force) ──
echo ""
echo "▸ Step 7: Force-pushing to $REMOTE_URL ..."
echo ""

git push -u origin HEAD:"$BRANCH" --force 2>&1 || {
  echo ""
  echo "Push failed. Common fixes:"
  echo "  • Create repo first: gh repo create $USERNAME/$REPO --public"
  echo "  • Auth: export GIT_TOKEN=ghp_xxx && git remote set-url origin https://\$GIT_TOKEN@github.com/$USERNAME/$REPO.git"
  exit 1
}

echo ""
echo "═══════════════════════════════════════════"
echo "  ✅ Pushed successfully!"
echo "  🔗 https://github.com/$USERNAME/$REPO"
echo ""
echo "  Next steps:"
echo "    1. Go to https://platform.efabless.com"
echo "    2. Create a new project"
echo "    3. Link your repo: $USERNAME/$REPO"
echo "    4. Select the active shuttle"
echo "    5. Submit!"
echo "═══════════════════════════════════════════"
